repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/lycheeverse/lychee.git
    rev: lychee-v0.18.1
    hooks:
      - id: lychee
        # Optionally include additional CLI arguments
        # Run lychee against the repository root (not just the staged files)
        # so that `exclude_path` from lychee.toml is respected.
        args: ["--no-progress", "--config", "./lychee.toml", "."]
        pass_filenames: false
  - repo: local
    hooks:
      - id: run-organize-script
        name: run-organize-script
        entry: pnpm
        args: ['run', 'organize']
        language: system
        pass_filenames: false
      - id: run-check-script
        name: run-check-script
        entry: pnpm
        args: ['run', 'check']
        language: system
        pass_filenames: false
      - id: run-structure-script
        name: run-structure-script
        entry: pnpm
        args: ['run', 'structure']
        language: system
        pass_filenames: false
